### ISSUE TITLE
Uploading a component deletes previously existing metadata attributes

### ISSUE THREAD

**Issue by dgarijo** [mintproject/wcm#11]
I annotated the Data catalog in WINGS with a new metadata property (dataCatalogId), defined at the "dataObject" (it's common for all files). Then I uploaded a component using WCM. The metadata property then disappeared.

**Comment by mosoriob** [comment]
Fixed it!
https://github.com/KnowledgeCaptureAndDiscovery/wings-client/commit/59144b2506c777bdc1882f682d65a66ad5907b83
